apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: chainsaw-test
spec:
  steps:
  - try:
    - apply:
        # resource
        file: ../base/todo-deployment.yaml
    - assert:
        # assertions
        file: assert.yaml