
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-local
  namespace: argocd
spec:
  destination:
    namespace: todo-local
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/overlays/local
    repoURL: https://github.com/RichGriffin/todo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
